# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_auto_20160312_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indoordatapoint',
            old_name='Indoor Humidity, RH%',
            new_name='Indoor Humidity',
        ),
    ]
