# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0003_auto_20160312_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indoordatapoint',
            old_name='Time of measurement',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='indoordatapoint',
            old_name='Indoor Humidity',
            new_name='indoor_humidity',
        ),
        migrations.RenameField(
            model_name='indoordatapoint',
            old_name='Indoor Temperature',
            new_name='indoor_temperature',
        ),
    ]
