# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0004_auto_20160312_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedroom_temperature', models.FloatField()),
                ('bedroom_humidity', models.FloatField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='IndoorDataPoint',
        ),
    ]
