# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0005_auto_20160312_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='bedroom_humidity',
            field=models.FloatField(verbose_name='Bedroom Humidity'),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='bedroom_temperature',
            field=models.FloatField(verbose_name='Bedroom Temperature'),
        ),
    ]
